# Generated by Django 5.2.8 on 2025-11-24 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaLugar',
            fields=[
                ('catlug_id', models.AutoField(primary_key=True, serialize=False)),
                ('catlug_descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('ciu_id', models.AutoField(primary_key=True, serialize=False)),
                ('ciu_descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RutaTuristica',
            fields=[
                ('rut_id', models.AutoField(primary_key=True, serialize=False)),
                ('rut_nombre', models.CharField(max_length=150)),
                ('rut_descripcion', models.TextField()),
                ('rut_duracion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoExperiencia',
            fields=[
                ('tipexp_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipexp_descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('tipousu_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipousu_turista', models.BooleanField(default=False)),
                ('tipousu_empresa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('lug_id', models.AutoField(primary_key=True, serialize=False)),
                ('lug_nombre', models.CharField(max_length=100)),
                ('lug_descripcion', models.CharField(max_length=300)),
                ('lug_ubicacion', models.CharField(max_length=200)),
                ('catlug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utravel.categorialugar')),
                ('ciu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utravel.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='LugarCategoria',
            fields=[
                ('lugcat_id', models.AutoField(primary_key=True, serialize=False)),
                ('catlug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utravel.categorialugar')),
                ('lug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utravel.lugares')),
            ],
        ),
        migrations.CreateModel(
            name='CiudadLugares',
            fields=[
                ('ciulug_id', models.AutoField(primary_key=True, serialize=False)),
                ('ciu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utravel.ciudad')),
                ('lug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utravel.lugares')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenLugares',
            fields=[
                ('logrut_id', models.AutoField(primary_key=True, serialize=False)),
                ('lugrut_orden', models.IntegerField()),
                ('lug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utravel.lugares')),
                ('rut_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utravel.rutaturistica')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usu_id', models.AutoField(primary_key=True, serialize=False)),
                ('usu_nombre', models.CharField(max_length=100)),
                ('usu_apellido', models.CharField(max_length=100)),
                ('usu_correo', models.EmailField(max_length=254, unique=True)),
                ('usu_contraseña', models.CharField(max_length=100)),
                ('usu_usunombre', models.CharField(max_length=100, unique=True)),
                ('ciu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utravel.ciudad')),
                ('tipousu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utravel.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('res_calificacion', models.IntegerField()),
                ('res_comentario', models.TextField()),
                ('res_fecha', models.DateField()),
                ('res_visible', models.BooleanField(default=True)),
                ('lug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utravel.lugares')),
                ('usu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utravel.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciaUsuario',
            fields=[
                ('prefusu_id', models.AutoField(primary_key=True, serialize=False)),
                ('prefusu_tipoExperiencia', models.CharField(max_length=100)),
                ('usu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utravel.usuario')),
            ],
        ),
    ]
