# Generated by Django 5.2.8 on 2025-11-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utravel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='ciudad_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='ciu_descripcion',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
