# Generated by Django 5.2.8 on 2025-11-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utravel', '0002_ciudad_ciudad_status_alter_ciudad_ciu_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoexperiencia',
            name='tipexp_status',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='ciudad_status',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
