# Generated by Django 5.2.8 on 2025-11-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utravel', '0003_tipoexperiencia_tipexp_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugares',
            name='lug_latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lugares',
            name='lug_longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lugares',
            name='lug_status',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
