# Generated by Django 5.2.8 on 2025-11-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utravel', '0003_tipoexperiencia_tipexp_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usu_status',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
