# Generated by Django 5.2.8 on 2025-12-06 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utravel', '0004_lugares_lug_latitud_lugares_lug_longitud_and_more'),
        ('utravel', '0004_rutaturistica_rut_estado'),
        ('utravel', '0004_usuario_usu_status'),
    ]

    operations = [
    ]
