# Generated by Django 5.2.8 on 2025-12-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utravel', '0005_merge_20251205_1730'),
        ('utravel', '0005_merge_20251205_2006'),
    ]

    operations = [
    ]
