# Generated by Django 5.2.8 on 2025-12-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utravel', '0006_merge_20251206_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugares',
            name='lug_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='lugares/'),
        ),
    ]
