# Generated by Django 5.2.8 on 2025-12-08 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utravel', '0007_lugares_lug_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugares',
            name='lug_imagen',
        ),
    ]
