# Generated by Django 5.2.8 on 2025-12-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utravel', '0008_remove_lugares_lug_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutaturistica',
            name='rut_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='rutas/'),
        ),
    ]
