# Generated by Django 5.2.8 on 2025-12-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utravel', '0009_rutaturistica_rut_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutaturistica',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rutaturistica',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
