# Generated by Django 5.2.8 on 2025-12-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utravel', '0010_rutaturistica_created_at_rutaturistica_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='res_status',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
