# Generated by Django 5.2.8 on 2025-12-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utravel', '0011_reseña_res_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugares',
            name='lug_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='lugares/'),
        ),
    ]
