# Generated by Django 5.2.8 on 2025-12-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utravel', '0012_lugares_lug_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usu_status',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=10),
        ),
    ]
